name: Build Docker image

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . -t docker.pkg.github.com/$GITHUB_REPOSITORY/app:latest
